services:
  # Metrics Service (your custom metrics)
  pipeline-metrics:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=200h'
    restart: unless-stopped
    depends_on:
      - pipeline-metrics

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana-dashboards:/etc/grafana/provisioning/dashboards
      - ./dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
    restart: unless-stopped
    depends_on:
      - prometheus

volumes:
  prometheus_data: